name       : mold
version    : 2.0.0
release    : 9
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v2.0.0.tar.gz : 2ae8a22db09cbff626df74c945079fa29c1e5f60bbe02502dcf69191cf43527b
license    : MIT
component  : programming.tools
summary    : A modern linker
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
avx2       : yes
lto        : yes
clang      : yes
builddeps  :
    - pkgconfig(libzstd)
    - pkgconfig(tbb)
    - mimalloc-devel
setup      : |
    %cmake_ninja -DMOLD_LTO=ON \
                 -DMOLD_MOSTLY_STATIC=OFF \
                 -DMOLD_USE_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_TBB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
