name       : mold
version    : 1.7.1
release    : 4
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v1.7.1.tar.gz : fa2558664db79a1e20f09162578632fa856b3cde966fbcb23084c352b827dfa9
license    : AGPL-3.0-or-later
component  : programming.tools
summary    : A modern linker
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
clang      : yes
builddeps  :
    - pkgconfig(libzstd)
    - pkgconfig(tbb)
    - mimalloc-devel
setup      : |
    %cmake_ninja -DMOLD_LTO=ON \
                 -DMOLD_MOSTLY_STATIC=OFF \
                 -DMOLD_USE_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_TBB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
