name       : mold
version    : 1.11.0
release    : 7
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v1.11.0.tar.gz : 99318eced81b09a77e4c657011076cc8ec3d4b6867bd324b8677974545bc4d6f
license    : AGPL-3.0-or-later
component  : programming.tools
summary    : A modern linker
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
clang      : yes
builddeps  :
    - pkgconfig(libzstd)
    - pkgconfig(tbb)
    - mimalloc-devel
setup      : |
    %cmake_ninja -DMOLD_LTO=ON \
                 -DMOLD_MOSTLY_STATIC=OFF \
                 -DMOLD_USE_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_MIMALLOC=ON \
                 -DMOLD_USE_SYSTEM_TBB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
