name       : mold
version    : 1.2.1
release    : 1
source     :
    - https://github.com/rui314/mold/archive/refs/tags/v1.2.1.tar.gz : 41868663ff18afee3fa35e5e3fdf3d9575eb2e4ff49967b8f42f479c61c1ec34
license    : AGPL-3.0-or-later
component  : programming.tools
summary    : A modern linker
description: |
    mold is a faster drop-in replacement for existing Unix linkers. mold is created for increasing developer productivity by reducing build time especially in rapid debug-edit-rebuild cycles.
clang      : yes
builddeps  :
    - intel-tbb-devel
    - mimalloc-devel
build      : |
    %make LIBDIR=%libdir% LTO=1 SYSTEM_MIMALLOC=1 SYSTEM_TBB=1 
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir% SYSTEM_MIMALLOC=1 SYSTEM_TBB=1
